---
title: "Project 2"
author: "Megan Joseph"
thanks: "Project repository available at: [https://github.com/meganajoseph/261a_project2](https://github.com/meganajoseph/261a_project2)."
date: today
date-format: long
abstract: ""
format: pdf
bibliography: references.bib
number-sections: true
---

# Introduction {#sec-intro}

the motivation for the analysis

Can college readiness, student demographics, school violence, and school demographics predict graduation rates in California high schools?

a brief overview of the broader context

the knowledge gap that is addressed by the paper

what was done in the analysis

the key findings and why they are important

the structure of the paper

This project draws from the data sources Common Core of Data, Small Area Income and Poverty Estimates, The Civil Rights Data Collection, EDFacts, Integrated Postsecondary Education Data System, College Scorecard, National Historical Geographic Information System, Federal Student Aid, National Association of College and University Business Officers, National Center for Charitable Statistics, Model Estimates of Poverty in Schools (MEPS), Equity in Athletics Data (EADA), and Campus Safety and Security [@Data_about].

# Data {#sec-data}

```{r}
#| include: false
#| warning: false
#| message: false

# load libraries
library(tidyverse)

# load data
schools <- read.csv("../data/EducationDataPortal_11.16.2025_Schools.csv")
dd <- read.csv("../data/EducationDataPortal_11.16.2025_datadictionary.csv")
grades <- read.csv("../data/EducationDataPortal_11.16.2025_grade_crdc.csv")
```

The data are from the Education Data Explorer from the Urban Institute's Center on Education Data and Policy. This tool compiles data from national data sources on schools, districts, and colleges in order to assist in creating insights to improve student outcomes [@Data_about].

I used this [query](https://educationdata.urban.org/data-explorer/explorer/?educationLevel=K-12&dataLevel=Schools&fipsNumbers=6&startYear=2016&endYear=2017&schoolLevel=high_cedp&charterSchoolOptions=1%2C0&timeframeType=date-range&togglesList=24-78%2C24-79%2C24-86%2C24-88%2C24-89%2C24-90%2C24-91%2C24-92%2C24-95%2C24-96%2C24-37%2C24-47%2C24-48%2C24-49%2C37-19%2C46-9%2C46-10%2C46-11%2C46-12%2C46-13%2C46-14%2C53-15%2C53-16%2C111-1349%2C49-1411%2C120-1333%2C120-1334%2C107-1326%2C107-1327%2C107-1328%2C107-1329%2C107-1330%2C107-1331%2C107-1332%2C118-1352%2C118-1354%2C118-1356%2C118-1358%2C118-1360%2C118-1362%2C118-1364%2C118-1366%2C118-1368%2C118-1369%2C118-1370%2C118-1371%2C118-1372%2C118-1373%2C118-1374%2C118-1375%2C28-97%2C60-98%2C24-100%2C24-101%2C24-102%2C24-103%2C127-1412%2C69-20%2C69-21%2C69-22%2C115-23%2C119-24%2C69-26%2C69-27%2C69-28%2C69-32%2C69-33%2C69-34%2C41-61%2C41-62%2C41-63%2C41-64%2C41-65%2C42-66%2C42-67%2C42-68%2C42-69%2C42-70%2C42-71%2C110-1335%2C110-1336%2C110-1337%2C110-1338%2C110-1339%2C110-1340%2C110-1341%2C110-1342%2C110-1343%2C110-1344%2C110-1345%2C110-1346%2C110-1347%2C110-1348%2C76-1%2C76-2%2C76-5%2C76-6%2C100-1138%2C52-1311%2C52-1312%2C52-1313%2C52-1314%2C52-1316%2C52-1318%2C123-1407%2C52-1319%2C123-1408%2C52-1320%2C123-1409%2C52-1321%2C52-1322%2C52-1323%2C52-1324%2C52-1325%2C123-1400%2C123-1401%2C123-1403%2C123-1404) to generate a dataset of high schools in California from 2016-2017 with information on school characteristics, absenteeism, college readiness, course offerings, student demographics, discipline, school safety, student outcomes, and teachers and staff [@Data]. The observational unit is an individual high school in California. The key variables of interest are student enrollment, an indicator stating whether a school is eligible for participation in either Target Assistance program or school-wide program authorized by Title I of Public Law 103-382, chronically absent students, students enrolled in the International Baccalaureate Diploma Program, students enrolled in the gifted and talented programs, students enrolled in at least one AP course, students who took one or more AP exams, number of students enrolled in a dual enrollment or dual credit program, students participating in the SAT and ACT tests, number of students eligible for free or reduced-price lunch, estimated percentage of students living in poverty, number of suspensions, number of full-time teachers, number of first-year teachers, number of full-time equivalent instructional aides or paraprofessionals, number of full-time equivalent school counselors, and teacher salary.

## Common Core of Data {#sec-cc}

The variables student enrollment, Title I eligibility, and the number of students eligible for free or reduced lunch are sourced from Common Core of Data (CCD) [@Data]. The CCD is the United States Department of Education's database on all public elementary and secondary schools and school districts [@CCD].

Student enrollment reports the number of students enrolled in the school. A school is Title I eligible if it is in a school district for children from low-income families [@NCES]. If a school is Title I eligible, there may be more students who are eligible for free or reduced price lunch. Interaction terms will be investigated for these variables.

I picked these variables because small schools have been linked to higher graduation rates, and students from low-income families tend to have higher dropout rates [@HP2030].

## The Civil Rights Data Collection {#sec-crdc}

The Civil Rights Data Collection comes from the United States Department of Education's Office for Civil Rights. This data is collection in order to ensure schools give students equal access to educational opportunities.

## Model Estimates of Poverty in Schools (MEPS) {#sec-meps}

## EDFacts {#sec-edfacts}

describe alternative/additional sources of data

highlight any critical characteristics of the data using visualizations or\
summary tables.

# Methods {#sec-methods}

present any model or statistical methods clearly using\
mathematical notation and plain English explanations.

Every symbol and component of the model should be introduced and described.

This section must clearly describe any relevant assumptions and whether they are met.

Describe possible limitations of your analysis.

describe the software used for implementation

include any necessary steps taken for model selection and validation.

# Results {#sec-results}

describe the fitted model and its implications.\
This section should include relevant tables, graphs, and quantitative results, as well as plain English explanations of all of these components.

Clearly explain what the model results show and connect your results to the central research question(s) and their broader context

# Discussion {#sec-disc}

A brief summary of the paper

Discussion of your key findings and what their implications are for your research question

Discussion of some potential weaknesses of your study

Identification of potential improvements and extensions or future areas of related research.

# References {#sec-ref}
